name: Preparing for Merging to main
run-name: ${{ github.actor }} is preparing for merging "${{ github.ref_name }}" to main
on:
  pull_request:
    types:
      - opened
    branches:
      - main 
jobs:
  Integration_Test_and_Check:
    runs-on: ubuntu-latest
    container: ruihe864/ccbr-github-playground:latest
    steps:
      - run: echo "Running test in Official R-base docker container with devtools"
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GIT_TOKEN}}
      
      - id: Build_check
        name: R Build and Checks
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          bash $current_wd/.github/workflows/Check_On_Merge_Main.sh "$current_wd"
          
      - name: Creating Realease branch
        if: ${{ failure() }}
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          cd $current_wd
          cat $(pwd)/NAMESPACE
          dt=`date '+%m_%d_%Y_%H_%M_%S'
          
          export MY_GIT_TOKEN=${{secrets.GIT_TOKEN}}
          export MY_GIT_USERNAME=${{secrets.GIT_USERNAME}}
          export MY_GIT_EMAIL=${{secrets.GIT_EMAIL}}
          
          git config --global user.name $MY_GIT_USERNAME
          git config --global user.email $MY_GIT_EMAIL
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git config --global --add safe.directory "$current_wd"
          
          git clone https://github.com/${GITHUB_REPOSITORY}.git
          
          cd ${GITHUB_REPOSITORY#*/}
          
          release_branch_name="Release_$dt"
          
          git checkout "$release_branch_name" 
          
          git push -f origin "$release_branch_name"
