name: Runing Check and Generating file for merging
run-name: ${{ github.actor }} is Runing Check and Generating file for merging
on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  Generating-NAMESPACE-file:
    runs-on: ubuntu-latest
    container: ruihe864/ccbr-github-playground:latest
    steps:
      - run: echo "Running test in Official R-base docker container"
      - uses: actions/checkout@v3
      
      - id: Build_check
        name: R Build and Checks
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          bash $current_wd/.github/workflows/Check_On_Merge.sh "$current_wd"
          
      - name: Upload NAMESPACE file
        if: if: ${{ success() }}
        run: |
          cat $(pwd)/NAMESPACE
          cd $current_wd
          
          export MY_GIT_TOKEN=${{secrets.GIT_TOKEN}}
          export MY_GIT_USERNAME=${{secrets.GIT_USERNAME}}
          export MY_GIT_EMAIL=${{secrets.GIT_EMAIL}}
          
          git config --global user.name $MY_GIT_USERNAME
          git config --global user.email $MY_GIT_EMAIL
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git config --global --add safe.directory "$current_wd"
          
          git add ./NAMESPACE ./man/* 
          git commit --amend -m "Upload generated NAMESPACE and /man"
          git push -f origin main
        
      
    
          
          
