name: Routine Push Check
run-name: ${{ github.actor }} is Routine Push Check
on:
  push:
    branches:
      - '*'
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    container: ruihe864/ccbr-github-playground:latest
    steps:
      - run: echo "Running test in Official R-base docker container"
      
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v3
        with:
           token: ${{secrets.GIT_TOKEN}}
           ref: ${{ steps.extract_branch.outputs.branch }}
           fetch-depth: 0
      
      - id: Build_check
        name: R Build and Checks
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          bash $current_wd/.github/workflows/Check_on_Commit.sh "$current_wd"
          
      - name: Undo Push
        if: ${{ failure() }}
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          
          export MY_GIT_TOKEN=${{secrets.GIT_TOKEN}}
          export MY_GIT_USERNAME=${{secrets.GIT_USERNAME}}
          export MY_GIT_EMAIL=${{secrets.GIT_EMAIL}}
          
          git config --global user.name $MY_GIT_USERNAME
          git config --global user.email $MY_GIT_EMAIL
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git config --global --add safe.directory "$current_wd"
          
          git branch ${GITHUB_REF}
          git reset --hard HEAD~1
          git commit --ammend -m "Undo last push due to error in test()"
          git push origin ${GITHUB_REF}
