name: Routine Push Check
run-name: ${{ github.actor }} is Runing Check and Generating NAMESPACE file
on:
  push
jobs:
  Routine_Check_for_Commit:
    runs-on: ubuntu-latest
    container: r-base:4.1.3
    steps:
      - run: echo "Running test in Official R-base docker container"
      - uses: actions/checkout@v3
      
      - id: Build_check
        name: R Build and Checks
        run: |
          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
          echo "$current_wd"
          bash $current_wd/.github/workflows/Install_and_run.sh "$current_wd"
          
      - name: Undo Push
        if: ${{ steps.Build_check.conclusion == 'failure' }}
        run: |
          cat $(pwd)/NAMESPACE
          cd $current_wd
          
          export MY_GIT_TOKEN=${{secrets.GIT_TOKEN}}
          export MY_GIT_USERNAME=${{secrets.GIT_USERNAME}}
          export MY_GIT_EMAIL=${{secrets.GIT_EMAIL}}
          
          git config --global user.name $MY_GIT_USERNAME
          git config --global user.email $MY_GIT_EMAIL
          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
          
          git config --global --add safe.directory $current_wd
          
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          
          git revert $git_hash
        
      
    
          
          
